### ISSUE TITLE
[Version 4.0.0] billing address

### ISSUE THREAD

**Issue by benju69** [checkout/frames-android#175]
**Is your feature request related to a problem? Please describe.**
Is it possible to don't show the billing address like before
`includeBilling(false)`
I don't want the address block, we handle addresses on our side

**Comment by chintan-soni-cko** [comment]
@benju69 Thank you for providing information regarding your concern.
We have the possibility to hide the address block in the styling.
1. if you using the default SDK style for the payment form please pass addressSummarystyle as null into PaymentformConfig. [Example here](https://github.com/checkout/frames-android/blob/master/example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt#:~:text=style%20%3D%20PaymentFormStyle()%2C)
 style = PaymentFormStyle(paymentDetailsStyle = PaymentDetailsStyle(addressSummaryStyle = null))
 2. If you using custom styling for paymentform, please pass null to addressSummaryStyle [Example here](https://github.com/checkout/frames-android/blob/master/example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentDetailsStyle.kt#:~:text=addressSummaryStyle%20%3D-,provideAddressSummaryStyle(),-%2C)
 3. If you are using custom theming style for payment form, please add setIsFieldHidden to true in order to hide billing form summary. [Example here](https://github.com/checkout/frames-android/blob/master/example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentFormTheme.kt#:~:text=.-,setIsFieldOptional,-(false))

Hope above solution helpful for you. Let me know if you need more help or any questions.

**Comment by benju69** [comment]
Ok with `paymentFormStyle.paymentDetailsStyle.addressSummaryStyle = null` Thanks

**Comment by Devs-97Eats** [comment]
Hi,

How can we set below fields like before?

`injectCardHolderName(this.firstName)`

`injectPhone( PhoneModel( "971", phone ) )`

`injectBilling( billingModel )`

**Comment by chintan-soni-cko** [comment]
Hi @Devs-97Eats , you can set fields for the billing form as we have had that possibility before.
Please find below solutions for it.
1. If you want to use the default billing form, use the SDK default style which will provide all default fields. See [example here](https://github.com/checkout/frames-android/blob/master/example_app_frames/src/main/java/com/checkout/example/frames/ui/screen/MainActivity.kt) [More details](https://github.com/checkout/frames-android/blob/master/frames/src/main/java/com/checkout/frames/style/screen/BillingAddressDetailsStyle.kt) 
2. If you want to inject specific fields along with desired order. Please have a look [example here](https://github.com/checkout/frames-android/blob/master/example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomBillingFormStyle.kt#:~:text=%40Suppress(%22,%7D)
3. If you want to inject custom fields by using theming style of SDK. Please have a look at [example here](https://github.com/checkout/frames-android/blob/master/example_app_frames/src/main/java/com/checkout/example/frames/paymentformstyling/CustomPaymentFormTheme.kt#:~:text=paymentFormComponents%20%3D%20DefaultPaymentFormTheme.providePaymentFormComponents,))
Please refer. [SDK documentation](https://www.checkout.com/docs/integrate/sdks/android-sdk/customize-the-android-sdk)

**Comment by Devs-97Eats** [comment]
> 

Thanks for the quick reply, I tried your solutions above but there are no related functions for injecting values and I only found style functions.

Note:
- I'm looking to hide address, bill views, and inject all customer details through the code, so only card number, expiry date, and CVV will be shown

**Comment by maxim-nosov-cko** [comment]
Hi @Devs-97Eats 

Billing address injection is not available right now.
If this functionality is needed please create a feature request ticket.

The Invalid country error looks like an implementation issue.
Please create a new ticket for further discussion with detailed code snippets and please clarify which customization approach is used (custom styling, default SDK styling, or theming).

***This ticket is closed and any further discussion should be moved to somewhere else.
