### ISSUE TITLE
Question about setting cardholder name

### ISSUE THREAD

**Issue by cornusmas** [checkout/frames-android#191]
Hi team
I want to set Cardholder's name on the background without showing any field about it. Is there any way for it?

**Comment by chintan-soni-cko** [comment]
Hi @cornusmas. Just to clarify your concern, would you like to add a pre-filled text label for cardholder name to the billing form page or payment page rather than the cardholder name input field? If yes, we are not currently supporting injecting a specific field text label instead of the input field. If it is required from your side, please create a separate feature request. 
If it does not help you, please provide more details on your concern. 
Thank you.

**Comment by cornusmas** [comment]
Thanks for response
I need to collect the user's cardholder's name for our rules. But it has to match 100% with the user's name in our app. So I have to set all cardholders' names by my side, not by the user's side. I set it already in the iOS project using this method in the picture from your iOS GitHub link. But in android, I can not find an equivalent of this.

<img width="1237" alt="Screenshot 2023-01-17 at 13 25 12" src="https://user-images.githubusercontent.com/96849434/212878438-246de520-80ed-47be-81bf-453c8b8f5cc7.png">

https://github.com/checkout/frames-ios

**Comment by patrick-hoban-cko** [comment]
Hey @cornusmas thanks for raising this. Injecting pre-filled data into the billing address and cardholder name fields was a feature we dropped to make a faster 4.0.0 release, but we would include this feature in a future release (no timelines at the moment though unfortunately).

Thanks for your patience on this.

**Comment by patrick-hoban-cko** [comment]
Hey @cornusmas, thank you for your patience on this, we have now released this change as part of the 4.1.0 release, which you can find here https://github.com/checkout/frames-android/issues/194. 

Have a look, and if you find any other issues, please do raise another query :)
