### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by gstephin** [checkout/frames-android#53]
While clearing the payment form for saved card transaction causes null pointer exception.

Process: com.bawiq, PID: 9804
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.checkout.android_sdk.View.CardDetailsView.resetFields()' on a null object reference
        at com.checkout.android_sdk.Utils.CustomAdapter.clearFields(CustomAdapter.java:77)
        at com.checkout.android_sdk.PaymentForm.clearForm(PaymentForm.java:529)

**Comment by shavinda-rabichandran-cko** [comment]
@gstephin Thank you for reporting this bug. 

I believe this issue occurs when if the `PaymentForm.clearForm()` function is used when the views are being generated. (i.e. in `onCreate`, `onStart` etc). Is that correct?

Could you please provide some insight on why the `clearForm()` function is being called at this stage rather than after a transaction.
