### ISSUE TITLE
Android 12 (API level 31) support.

### ISSUE THREAD

**Issue by v-sulimov** [checkout/frames-android#66]
Hi! 
We use your library in our project and everything works fine, but I have a question. At the moment, the documentation specifies the requirement "Target API level 30".
Is there any information when API level 31 will be supported? 
We need to bump the targetSdk in our applicatrion, but I'm not sure that your library will function correctly in this case.

Sincerely, Vitaly Sulimov.

**Comment by shavinda-rabichandran-cko** [comment]
@v-sulimov Thanks for your query.

The framework was last fully validated with `targetApi  == 30`, which is why we have indicated this in the README.

The library itself does not "require" the `targetSdk` to be at 30. Considering the behavioural changes included in [Android 12 - API 31](https://developer.android.com/about/versions/12/behavior-changes-12) the library should not behave any differently should you decide to increase the `targetSdk` of your application to 31.

Once we have had a chance to validate the library against a device on API 31, I will update the README to reflect this (and reword the statement to improve clarity). In the meantime if you experience any issues with the library with the `targetSdk` set to 31 please let report it here so we can address the issues.

**Comment by v-sulimov** [comment]
@shavinda-rabichandran-cko 
Got it. 
Thank you very much for the fast response. We will bump the targetSdk in the application and, if anything, report issues.

**Comment by shavinda-rabichandran-cko** [comment]
PR #69 has been merged which has the update to the README to improve clarity of the requirements section.

The `targetSdk` of the reference application has been increased to 31 and facilitate testing. If there are any related issues, these will be addressed in the upcoming scheduled release `3.1.0`.

Closing issue since the document has been update to provide clarity. Please re-open or open a new issue if there are any compatibility issues with targetSdk 31.

**Comment by shavinda-rabichandran-cko** [comment]
Version `3.1.0` has been released.
